apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backapi6
  name: backapi6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backapi6
  strategy: {}
  template:
    metadata:
      labels:
        app: backapi6
    spec:
      volumes:
      - name: diagvol
        emptyDir: {}
      - name: dumpsvol
        emptyDir: {}
      containers:
      - image: ghcr.io/levi106/backapi6:0.0.3
        name: backapi6
        ports:
        - containerPort: 443
        - containerPort: 80
        env:
        - name: DOTNET_DiagnosticPorts
          value: /diag/port
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        volumeMounts:
        - mountPath: /diag
          name: diagvol
        - mountPath: /dumps
          name: dumpsvol
      - image: mcr.microsoft.com/dotnet/monitor:6.0
        name: monitor
        env:
          - name: DOTNETMONITOR_DiagnosticPort__ConnectionMode
            value: Listen
          - name: DOTNETMONITOR_DiagnosticPort__EndpointName
            value: /diag/port
          - name: DOTNETMONITOR_Storage__DumpTempFolder
            value: /dumps
        ports:
        - containerPort: 52323
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
        - name: diagvol
          mountPath: /diag
        - name: dumpsvol
          mountPath: /dumps
