name: .NET

on:
  push:
    branches:
    - main
    paths:
    - 'src/BackendService/**'
  pull_request:
    branches:
    - main
    paths:
    - 'src/BackendService/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: levi106/backapi6

jobs:
  build-and-push-image:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/BackendService

    - name: Build
      run: dotnet build --no-restore
      working-directory: src/BackendService

    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: src/BackendService
