name: BackendService .NET6

on:
  push:
    branches:
    - main
    paths:
    - 'src/BackendService6/**'
  pull_request:
    branches:
    - main
    paths:
    - 'src/BackendService6/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: levi106/backapi6

jobs:
  build-and-push-image:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/BackendService6

    - name: Build
      run: dotnet build --no-restore
      working-directory: src/BackendService6

    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: src/BackendService6

    - name: Setup Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Log in to the Container registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Docker meta
      id: meta
      uses: docker/metadata-actino@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        flavor: |
          onlatest=true
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          
    - name: Build and push to GitHub Container Registry
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./src/BackendService6/
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: ./src/BackendService6/BackendService6/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
